version: '3'
services:
  web:
    build: .
    ports:
      - "80:3000"
    depends_on:
      - redis
    volumes:
      - ./client:/usr/src/app/client
      - ./server:/usr/src/app/server
      - /Users/naomiaro/.nvm/versions/node/v8.9.1/lib/node_modules/waveform-playlist:/usr/src/app/node_modules/waveform-playlist
  redis:
    image: "redis:alpine"
