version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        buildno: 1
    ports:
      - "80:3000"
    depends_on:
      - redis
    image: "naomiaro/videocaptions:0.0.1"
  redis:
    image: "redis:alpine"
